# Generated by Django 5.0.4 on 2024-04-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='low', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='priorities',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=6),
        ),
    ]
